# Properties of Dot Product - Lab

## Introduction

In this lab, you'll be practicing some interesting properties of a Dot Product-type matrix multiplication. Understanding these properties will become useful as you move forward with machine learning. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - matrix multiplication is distributive

### Prove that $A \cdot (B+C) = (A \cdot B + A \cdot C) $

In [1]:
# Your code here
import numpy as np

In [6]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[7, 3, 1], [8, 4,9], [13,8,4]])
C = np.array([[8, 4, 5], [2, 12, 9], [11, 6, 13]])

In [10]:
left = A.dot(B+C)
right = A.dot(B) + A.dot(C)
left == right

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Associative Property - matrix multiplication is associative
### Prove that $A \cdot (B \cdot C) = (A \cdot B) \cdot C $

In [14]:
# Your code here 
A.dot(B.dot(C)) == A.dot(B).dot(C)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Commutative Property - matrix multiplication is NOT commutative
### Prove that for matrices, $A \cdot B \neq B \cdot A $

In [15]:
# Your code here 
A.dot(B) != B.dot(A)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors,  $x^T \cdot y = y^T \cdot x$
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [16]:
# Your code here 
x = np.array([1,2,3,4])
y = np.array([5,7,2,5])

In [18]:
x.T.dot(y) == y.T.dot(x)

True

## Simplification of the matrix product
### Prove that $ (A \cdot B)^T = B^T \cdot A^T $

In [19]:
# Your code here 
A.dot(B).T == B.T.dot(A.T)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Summary 

You've seen enough matrix algebra by now to solve a problem of linear equations as you saw earlier. You'll now see how to do this next. 